---
title: Tool Links
---

## Other visualization tools

```{r}
#| echo: false

library(pixture)

paths <- c(
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/ggalign.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/FigureYa.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/Awesome-genome-vis.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/Marsilea.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/tidyplots.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/ggrecipes.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/scidraw.png"
)

title <- c(
  "ggalign-gallery",
  "FigureYa",
  "awesome-genome-visualization",
  "Marsilea",
  "tidyplots",
  "ggrecipes",
  "scidraw"
)

describe <- c(
  "Integrative Composable Visualization",
  "317 Visualization Code Framework",
  "A list of genome visualization programs",
  "Declarative creation of composable visualization",
  "Tidy plots for scientific publications",
  "Recipes for ggplot2 visualizations",
  "Scientific drawing and illustration tool"
)

link <- c(
  "https://yunuuuu.github.io/ggalign-gallery/",
  "https://ying-ge.github.io/FigureYa/",
  "https://cmdcolin.github.io/awesome-genome-visualization/",
  "https://marsilea.rtfd.io/",
  "https://jbengler.github.io/tidyplots/",
  "https://ignophi.github.io/ggrecipes/index.html",
  "https://scidraw.msttnote.cn/"
)

captions <- paste0(
  "<div style='line-height:0.1;'>",
  paste0("<div style='font-size:1.0rem;margin-bottom:0.2em;line-height:1;color:#34495e;'><b>", title, "</b></div>"),
  paste0("<div style='line-height:1.2;font-size:0.7rem;color:#808b96;'>", describe, "</div>"),
  "</div>"
)

pixgallery(
  path = paths,
  caption = captions,
  caption_valign = "below",
  caption_halign = "center",
  link = link,
  h = "250px",
  w = "250px", 
  border_radius = "10px",
  gap = "10px",
  layout = "fixed"
)
```



## Web visualization applications

```{r}
#| echo: false

paths <- c(
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/Hiplot.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/UCSCXenaShiny.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/CNScolor.png"
)

title <- c(
  "Hiplot",
  "UCSCXenaShiny",
  "CNScolor"
)

describe <- c(
  "Biomedical Data Visualization",
  "UCSCXenaShiny Hub Shiny App",
  "Open source CNS color website"
)

link <- c(
  "https://hiplot.cn/",
  "https://shiny.zhoulab.ac.cn/UCSCXenaShiny/",
  "https://tigerz.shinyapps.io/CNScolor/"
)

captions <- paste0(
  "<div style='line-height:0.1;'>",
  paste0("<div style='font-size:1.0rem;margin-bottom:0.2em;line-height:1;color:#34495e;'><b>", title, "</b></div>"),
  paste0("<div style='line-height:1.2;font-size:0.7rem;color:#808b96;'>", describe, "</div>"),
  "</div>"
)

pixgallery(
  path = paths,
  caption = captions,
  caption_valign = "below",
  caption_halign = "center",
  link = link,
  h = "250px",
  w = "250px", 
  border_radius = "10px",
  gap = "10px",
  layout = "fixed"
)
```




