---
title: "条码图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Barcode Plot` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/barcode-plot?lang=zh_cn>
:::

条码图适用于展示大量数据的分布情况。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggplot2)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

案例数据为某商品在三个地区各500个门店的销售额。

```{r load data, message=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/barcode-plot/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 查看数据
head(data)
```

## 可视化

```{r fig-1Barcode-plot}
#| label: fig-1Barcode-plot
#| fig-cap: "条码图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 8
#| warning: false

# 条码图
p <- ggplot(data, aes(x = sales, y = region)) +
  geom_tile(width = 0.01, height = 0.9, fill = "#606fcc") + # 控制条带的宽度和高度
  theme_bw() +
  labs(title = "Sales report", x = "Sales", y = "Region") +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

通过条码图可以看到该商品在广东和福建地区销售额分布在50左右的门店数量较多，且在广东各门店之间销售额差异较小，分布较集中。

::: callout-tip
**特殊参数: **

- **width**：条带宽度
- **height**：条带高度
- **color**：条带颜色
:::

