---
title: 误差线柱状图
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Barplot (errorbar)` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/barplot-errorbar?lang=zh_cn>
:::

带误差线和误差组的条形图。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggplot2`; `Rmisc`; `ggpubr`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("Rmisc", quietly = TRUE)) {
  install.packages("Rmisc")
}
if (!requireNamespace("ggpubr", quietly = TRUE)) {
  install.packages("ggpubr")
}


# 加载包
library(data.table)
library(jsonlite)
library(ggplot2)
library(Rmisc)
library(ggpubr)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

数据表:

第一列: (数值) Y 轴值。

第二列: (数值或字符串) X 轴类别。

```{r load data, message=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/barplot-errorbar/data.json")$exampleData[[1]]$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data[, 2] <- factor(data[, 2], levels = unique(data[, 2]))
data_sd <- summarySE(data, measurevar = colnames(data)[1], groupvars = colnames(data)[2])

# 查看数据
head(data_sd)
```

## 可视化

```{r fig-1barplot-errorbar}
#| label: fig-1barplot-errorbar
#| fig-cap: "误差线柱状图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false

# 误差线柱状图
p <- ggplot(data_sd, aes(x = data_sd[, 1], y = data_sd[, 3], fill = data_sd[, 1])) +
  geom_bar(stat = "identity", color = "black", 
           position = position_dodge(), alpha = 1) +
  geom_errorbar(aes(ymin = data_sd[, 3] - sd, ymax = data_sd[, 3] + sd),
                width = 0.2,
                position = position_dodge(0.9)) +
  labs(title = "Barplot (errorbar)", x = colnames(data_sd)[1], 
       y = colnames(data_sd)[3], fill = colnames(data_sd)[1]) +
  geom_jitter(data = data, aes(data[, 2], data[, 1], fill = data[, 2]), size = 2, fill = "black", pch = 19, width = 0.2) +
  stat_compare_means(data = data, aes(data[, 2], data[, 1], fill = data[, 2]),
                     label = "p.format", ref.group = ".all.", vjust = 1, 
                     method = "t.test") +
  scale_fill_manual(values = c("#E64B35FF","#4DBBD5FF","#00A087FF","#3C5488FF")) +
  theme_bw() +
  ylim(0,100) +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```



