---
title: "多柱状图和线图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Multiple Barplot&Line` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/barplot-line-multiple?lang=zh_cn>
:::

在一个图表中显示多个条形图或线形图。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggplot2`; `reshape2`; `ggthemes`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("reshape2", quietly = TRUE)) {
  install.packages("reshape2")
}
if (!requireNamespace("ggthemes", quietly = TRUE)) {
  install.packages("ggthemes")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggplot2)
library(reshape2)
library(ggthemes)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

具有多列数据（数字）的数据框。

```{r load data, message=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/barplot-line-multiple/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data_melt <- melt(data, id.vars = colnames(data)[1])
data_melt[, 1] <- factor(data_melt[, 1], level = unique(data_melt[, 1]))

# 查看数据
head(data)
```

## 可视化

### 1. 多线图

```{r fig-1Barplot-line-multiple1}
#| label: fig-1Barplot-line-multiple1
#| fig-cap: "多线图"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 8
#| warning: false

# 多线图
p <- ggplot(data = data_melt, aes(x = age, y = value, group = variable,
                                  colour = variable)) +
  geom_line(alpha = 1, size = 1) +
  geom_point(aes(shape = variable), alpha = 1, size = 3) +
  labs(title = "Line (Multiple)", x = "X Lable", y = "Value") +
  scale_color_manual(values = c("#3B4992FF","#EE0000FF","#008B45FF","#631879FF",
                               "#008280FF","#BB0021FF")) +
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

### 2. 多柱状图

```{r fig-1Barplot-line-multiple2}
#| label: fig-1Barplot-line-multiple2
#| fig-cap: "多柱状图"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 8
#| warning: false

# 多柱状图
p <- ggplot(data = data_melt, aes(x = age, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = position_dodge(), colour = "black",
           alpha = 1) +
  labs(title = "", x = "X Lable", y = "Value") +
  
  scale_fill_manual(values = c("#3B4992FF","#EE0000FF","#008B45FF","#631879FF",
                               "#008280FF","#BB0021FF")) +
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```



