---
title: "气泡图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Bubble` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/bubble?lang=zh_cn>
:::

气泡图是在散点图的基础上，用气泡的大小来展示第三个变量,从而能够同时对三个变量进行对比分析的统计图表。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggplot2`; `stringr`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("stringr", quietly = TRUE)) {
  install.packages("stringr")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggplot2)
library(stringr)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

载入数据为 GO Term, Gene Ridio,基因数和 P 值。

```{r load data, message=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/bubble/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data[, 1] <- str_to_sentence(str_remove(data[, 1], pattern = "\\w+:\\d+\\W"))
topnum <- 7
data <- data[1:topnum, ]
data[, 1] <- factor(data[, 1], level = rev(unique(data[, 1])))

# 查看数据
head(data)
```

## 可视化

```{r fig-1Bubble}
#| label: fig-1Bubble
#| fig-cap: "气泡图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false

# 气泡图
p <- ggplot(data, aes(Ratio, Term)) +
  geom_point(aes(size = Count, colour = -log10(PValue))) +
  scale_colour_gradient(low = "#00438E", high = "#E43535") +
  labs(colour = "-log10 (PValue)", size = "Count", x = "Ratio", y = "Term", 
       title = "Bubble Plot") +
  scale_x_continuous(limits = c(0, max(data$Ratio) * 1.2)) +
  guides(color = guide_colorbar(order = 1), size = guide_legend(order = 2)) +
  scale_y_discrete(labels = function(x) {str_wrap(x, width = 65)}) +
  theme_bw() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

x 轴表示 Gene Ridio，y 轴是 GO Term; 点的大小表示基因数，点的颜色代表 P 值的高低。




