---
title: "圆堆图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Circle Packing` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/circle-packing?lang=zh_cn>
:::

用于展示不同类型之间的数量差异。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `packcircles`; `ggplot2`; `viridis`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("packcircles", quietly = TRUE)) {
  install.packages("packcircles")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("viridis", quietly = TRUE)) {
  install.packages("viridis")
}

# 加载包
library(data.table)
library(jsonlite)
library(packcircles)
library(ggplot2)
library(viridis)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/circle-packing/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
packing <- circleProgressiveLayout(data[["v"]], sizetype = "area")
data <- cbind(data, packing)
dat_gg <- circleLayoutVertices(packing, npoints = 50)
colors <- c("#E57164","#F8ECA7","#9389C1","#3F9C78","#769F8D","#E5F9A9","#7CE9A4",
            "#CE9FCA","#78F197","#8BB085","#D88880","#A6E4C3","#F7F6B1","#C5E69A",
            "#F45FDE","#5CF371","#9259CF","#2B6D9B","#F3C096","#EEADBE")
dat_gg$value <- rep(colors, each = 51)

# 查看数据
head(data)
```

## 可视化

```{r fig-1Circle-packing}
#| label: fig-1Circle-packing
#| fig-cap: "圆堆图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 8
#| warning: false
#| message: false

# 圆堆图
p <- ggplot() +
  geom_polygon(data = dat_gg, aes(x, y, group = id, fill = value), colour = "black", alpha = 0.4) +
  scale_fill_manual(values = magma(nrow(data))) +
  theme_void() +
  theme(legend.position = "none") +
  coord_equal() +
  scale_size_continuous(range = c(2.3, 4.5)) +
  geom_text(data = data, aes(x, y, size = v, label = g), vjust = 0) +
  geom_text(data = data, aes(x, y, label = v, size = v), vjust = 1.2)

p
```


