---
title: "相关性热图 (Corrplot)"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Corrplot` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/corrplot?lang=zh_cn>
:::

相关性热图是一种分析多个变量，两两之间相关性的图形。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `corrplot`; `ggcorrplot`; `ggplotify` 

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("corrplot", quietly = TRUE)) {
  install.packages("corrplot")
}
if (!requireNamespace("ggcorrplot", quietly = TRUE)) {
  install.packages("ggcorrplot")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# 加载包
library(data.table)
library(jsonlite)
library(corrplot)
library(ggcorrplot)
library(ggplotify)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

载入数据为基因名称及每个样本的表达量。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/corrplot/data.json")$exampleData[[1]]$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data <- data[!is.na(data[, 1]), ]
idx <- duplicated(data[, 1])
data[idx, 1] <- paste0(data[idx, 1], "--dup-", cumsum(idx)[idx])
rownames(data) <- data[, 1]
data <- data[, -1]
str2num_df <- function(x) {
  final <- NULL
  for (i in seq_len(ncol(x))) {
    final <- cbind(final, as.numeric(x[, i]))
  }
  colnames(final) <- colnames(x)
  return(final)
}
tmp <- str2num_df(t(data))
corr <- round(cor(tmp, use = "na.or.complete", method = "pearson"), 3)
p_mat <- round(cor_pmat(tmp, method = "pearson"), 3)

# 查看数据
head(data)
```

## 可视化

```{r fig-1Corrplot}
#| label: fig-1Corrplot
#| fig-cap: "相关性热图 (Corrplot)"
#| out.width: "95%"
#| fig-height: 9
#| fig-width: 9
#| warning: false
#| message: false

# 相关性热图 (Corrplot)
p <- as.ggplot(function(){
  corrplot(
    corr, 
    method = "circle", 
    type = "upper",
    tl.col = "black", 
    diag = F,
    col = colorRampPalette(c("#4477AA", "#FFFFFF", "#BB4444"))(200),
    order = "hclust",
    hclust.method = "ward.D2")
  }) +
  xlab("") + ylab("") +
  ggtitle("Cor Heatmap Plot") +
  theme_void() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_blank(), axis.text.y = element_blank(),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))
p
```

红色系表示两个基因之间呈正相关，蓝色系表示两个基因之间呈负相关，每一格中的数字表示相关系数。


