---
title: "D3 词云"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `D3 Wordcloud` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/d3-wordcloud?lang=zh_cn>
:::

词云图展示。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `d3wordcloud`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("d3wordcloud", quietly = TRUE)) {
  remotes::install_github("jbkunst/d3wordcloud")
}

# 加载包
library(data.table)
library(jsonlite)
library(d3wordcloud)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/d3-wordcloud/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
row.names(data) <- data[, 1]

# 查看数据
head(data)
```

## 可视化

```{r fig-1D3-wordcloud}
#| label: fig-1D3-wordcloud
#| fig-cap: "D3 词云"
#| out.width: "95%"
#| warning: false
#| message: false

# D3 词云
p <- d3wordcloud(
  words = data[, 1], 
  freqs = data[, 2],
  padding = 0,
  rotate.min = 0,
  rotate.max = 0,
  size.scale = "linear",
  color.scale = "linear",
  spiral = "archimedean",
  font = "Arial",
  rangesizefont = c(10, 90)
)

p
```






