---
title: "镜像密度图和直方图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Mirror Density & Histogram` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/density-hist-mirror?lang=zh_cn>
:::

镜像密度图和直方图是一种使用上下双侧绘制方法用来观察连续型变量分布的图形。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggplot2`; `ggthemes`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("ggthemes", quietly = TRUE)) {
  install.packages("ggthemes")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggplot2)
library(ggthemes)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/density-hist-mirror/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
sides <- data[1,]
data <- data[-1,]
for (i in 1:ncol(data)) {
  data[,i] <- as.numeric(data[,i])
}

# 查看数据
head(data)
```

## 可视化

### 1. 镜像密度图

```{r fig-1Density-mirror}
#| label: fig-1Density-mirror
#| fig-cap: "镜像密度图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false
#| message: false

# 镜像密度图
p <- ggplot(data, aes(x=x))
colrs <- c("#e64b35ff","#4dbbd5ff","#00a087ff","#3c5488ff","#f39b7fff","#8491b4ff")
colrs2 <- colnames(data)
for (i in seq_len(length(sides))) {
  eval(parse(
    text = sprintf("p <- p + geom_density(aes(x = %s, y = %s..density.., color = '%s', fill = '%s'), kernel = '%s')", 
                   colnames(data)[i], ifelse(sides[i] == "top", "", "-"), colnames(data)[i],
                   colnames(data)[i], "gaussian")
    ))
  names(colrs)[i] <- colnames(data)[i]
  names(colrs2)[i] <- colrs[i]
}
p <- p + 
  ggtitle("") +
  scale_fill_manual(values=colrs, name="Densities") +
  scale_color_manual(values=colrs, name="Densities") +
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```


### 2. 镜像直方图

```{r fig-2Hist-mirror}
#| label: fig-2Hist-mirror
#| fig-cap: "镜像直方图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false
#| message: false

# 镜像直方图
p <- ggplot(data, aes(x=x))
colrs <- c("#e64b35ff","#4dbbd5ff","#00a087ff","#3c5488ff","#f39b7fff","#8491b4ff")
colrs2 <- colnames(data)
for (i in seq_len(length(sides))) {
  eval(parse(
    text = sprintf("p <- p + geom_histogram(aes(x = %s, y = %s..density.., color = '%s', fill = '%s'), bins = %s)", 
                   colnames(data)[i], ifelse(sides[i] == "top", "", "-"),
                   colnames(data)[i], colnames(data)[i], 35)))
  names(colrs)[i] <- colnames(data)[i]
  names(colrs2)[i] <- colrs[i]
}
p <- p + 
  ggtitle("") +
  scale_fill_manual(values=colrs, name="Densities") +
  scale_color_manual(values=colrs, name="Densities") +
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```



