---
title: "环形图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Donut` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/donut?lang=zh_cn>
:::

环形图是饼图的一种变体，它有一个允许包含数据整体额外信息的空白中心。且与饼图目的一致，都是用来说明数据比例。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggplot2)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

载入数据为不同分组及其数据。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/donut/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data$fraction <- data[, 2] / sum(data[, 2])
data$ymax <- cumsum(data$fraction)
data$ymin <- c(0, head(data$ymax, n = -1))
data$labelPosition <- (data$ymax + data$ymin) / 2
data$label <- paste0(data[, 1], "\n",
  "(", data[, 2], ", ", sprintf("%2.2f%%", 100 * data[, 2] / sum(data[, 2])), ")",
  sep = ""
)

# 查看数据
head(data)
```

## 可视化

```{r fig-1Donut}
#| label: fig-1Donut
#| fig-cap: "环形图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 5
#| warning: false
#| message: false

# 环形图
p <- ggplot(data, aes_(ymax = as.name("ymax"), ymin = as.name("ymin"), 
                       xmax = 4, xmin = 3, fill = as.name(colnames(data)[1]))) +
  geom_rect() +
  geom_text(x = 5 + (4 - 5) / 3,
            aes(y = labelPosition, label = label), size = 4) +
  coord_polar(theta = "y") +
  xlim(c(2, 5)) +
  scale_fill_manual(values = c("#00468BCC","#ED0000CC","#42B540CC","#0099B4CC")) +
  ggtitle("Donut Plot") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none")

p
```

不同颜色表示不同组群，不同面积表示数据及占比。

