---
title: "简易 SOM"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Easy SOM` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/easy-som?lang=zh_cn>
:::

建立 SOM 模型，并可视化结果。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `GGally`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("kohonen", quietly = TRUE)) {
  install.packages("kohonen")
}

# 加载包
library(data.table)
library(jsonlite)
library(kohonen)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/easy-som/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
target <- data[,1]
target <- factor(target, levels = unique(target))
data <- data[,-1]
data <- as.data.frame(data)
for (i in 1:ncol(data)) {
  data[,i] <- as.numeric(data[,i])
}
data <- as.matrix(data)
set.seed(7)
kohmap <- xyf(scale(data), target, grid = somgrid(xdim=6, ydim=4, topo="hexagonal"), rlen=100)

color_key <- c("#A50026","#D73027","#F46D43","#FDAE61","#FEE090","#FFFFBF","#E0F3F8",
               "#ABD9E9","#74ADD1","#4575B4","#313695")
colors <- function (n, alpha, rev = FALSE) {
  colorRampPalette(color_key)(n)
}

# 查看数据
head(data)
```

## 可视化

```{r fig-1Eeasy-som}
#| label: fig-1Eeasy-som
#| fig-cap: "简易 SOM"
#| out.width: "95%"
#| fig-height: 8
#| fig-width: 8
#| warning: false
#| message: false

# 简易 SOM
p <- function () {
  par(mfrow = c(3,2))
  xyfpredictions <- classmat2classvec(getCodes(kohmap, 2))
  plot(kohmap, type="counts", col = as.integer(target),
       palette.name = colors,
       pchs = as.integer(target), 
       main = "Counts plot", shape = "straight", border = NA)
  
  som.hc <- cutree(hclust(object.distances(kohmap, "codes")), 3)
  add.cluster.boundaries(kohmap, som.hc)

  plot(kohmap, type="mapping",
       labels = as.integer(target), col = colors(3)[as.integer(target)],
       palette.name = colors,
       shape = "straight",
       main = "Mapping plot")

  ## 根据预测的类别标签为单元添加背景颜色
  xyfpredictions <- classmat2classvec(getCodes(kohmap, 2))
  bgcols <- colors(3)
  plot(kohmap, type="mapping", col = as.integer(target),
       pchs = as.integer(target), bgcol = bgcols[as.integer(xyfpredictions)],
       main = "Another mapping plot", shape = "straight", border = NA)
  
  similarities <- plot(kohmap, type="quality", shape = "straight",
                       palette.name = colors)
  
  plot(kohmap, type="codes", shape = "straight", 
       main = c("Codes X", "Codes Y"), palette.name = colors)
}

p()
```


