---
title: "鱼形图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Fishplot` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/fishplot?lang=zh_cn>
:::

克隆演化分析。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `fishplot`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("fishplot", quietly = TRUE)) {
  remotes::install_github("chrisamiller/fishplot")
}

# 加载包
library(data.table)
library(jsonlite)
library(fishplot)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/fishplot/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 查看数据
head(data)
```

- **timepoints**：为矩阵的每一列指定时间点

- **parents**：指定克隆之间的父母关系

- **samplename**：样品名称（支持多个样品）

- **other**：包含所有时间点所有克隆的肿瘤比例估计值的数值矩阵

## 可视化

```{r fig-1Fan}
#| label: fig-1Fan
#| fig-cap: "鱼形图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 10
#| warning: false
#| message: false

## 创建一个 fish 对象
fish = createFishObject(as.matrix(data[,4:7]), parents=data$parents, 
                        timepoints=data$timepoints, 
                        col = c("#888888","#e8130c","#f8150d","#55158f"))
## 计算绘图的布局
fish = layoutClones(fish)
## 使用 splining 方法绘制图（推荐），并提供标签和绘图标题的时间点
fishPlot(fish,shape="spline", title.btm="Sample1", title = "Fishplot",
         cex.title=1, vlines=c(0,30,75,150), 
         vlab=c("Day 0","Day 30","Day 75","Day 150"))
```

