---
title: "甘特图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Gantt` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/gantt?lang=zh_cn>
:::

甘特图是一种用来说明项目进度条形图。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `tidyverse`; `ggthemes`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("tidyverse", quietly = TRUE)) {
  install.packages("tidyverse")
}
if (!requireNamespace("ggthemes", quietly = TRUE)) {
  install.packages("ggthemes")
}

# 加载包
library(data.table)
library(jsonlite)
library(tidyverse)
library(ggthemes)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

载入数据为 4 个样本即四位患者，3 个项目即 3 种治疗方法，以及每种治疗方法的起止时间。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/gantt/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
usr_ylab <- colnames(data)[1]
if (!is.numeric(data[, 2])) {
  data[, 2] <- factor(data[, 2], levels = unique(data[, 2]))
}
data_gather <- gather(data, "state", "date", 3:4)
sample <- levels(data_gather$sample)
data_gather$sample <- factor(data_gather$sample,
  levels = rev(unique(data_gather$sample))
)

# 查看数据
head(data_gather)
```

## 可视化

```{r fig-1Gantt}
#| label: fig-1Gantt
#| fig-cap: "甘特图"
#| out.width: "95%"
#| fig-height: 6
#| fig-width: 10
#| warning: false
#| message: false

# 甘特图
p <- ggplot(data_gather, aes(date, sample, color = item)) +
  geom_line(size = 10, alpha = 1) +
  labs(x = "Time", y = "sample", title = "Gantt Plot") +
  theme(axis.ticks = element_blank()) +
  scale_color_manual(values = c("#e04d39","#5bbad6","#1e9f86")) +
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

横轴表示时间进度，纵轴表示 4 位患者，3 种颜色表示 3 种治疗方法，该图可以观测到每位患者不同治疗方法使用的时间进度。

