---
title: "分布图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Dist Plot` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/ggdist?lang=zh_cn>
:::

分布图是一种采用置信分布的可视化图形。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggdist`; `tidyr`; `broom`; `modelr`; `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggdist", quietly = TRUE)) {
  install.packages("ggdist")
}
if (!requireNamespace("tidyr", quietly = TRUE)) {
  install.packages("tidyr")
}
if (!requireNamespace("broom", quietly = TRUE)) {
  install.packages("broom")
}
if (!requireNamespace("modelr", quietly = TRUE)) {
  install.packages("modelr")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggdist)
library(tidyr)
library(broom)
library(modelr)
library(ggplot2)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

载入数据为 5 种条件及其对应的值。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/ggdist/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data[, 1] <- factor(data[, 1], levels = rev(unique(data[, 1])))
data <- tibble(data)
data2 = lm(response ~ condition, data = data)
data3 <- data_grid(data, condition) %>%
  augment(data2, newdata = ., se_fit = TRUE)

# 查看数据
head(data)
```

## 可视化

```{r fig-1ggdist}
#| label: fig-1ggdist
#| fig-cap: "分布图"
#| out.width: "95%"
#| fig-height: 3
#| fig-width: 4
#| warning: false
#| error: false
#| message: false

# 分布图
p <- ggplot(data3, aes_(y = as.name(colnames(data[1])))) +
  stat_dist_halfeye(aes(dist = "student_t", arg1 = df.residual(data2),
                        arg2 = .fitted, arg3 = .se.fit),
                    scale = .5) +
  geom_point(aes_(x = as.name(colnames(data[2]))),
             data = data, pch = "|", size = 2,
             position = position_nudge(y = -.15)) +
  ggtitle("ggdist Plot") + 
  xlab("response") + ylab("condition") +
  theme_ggdist() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

图示给出的是条件下均值的置信度分布，可以看出 5 种条件下对应值的大致分布情况。




