---
title: "GGPubr 箱线图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `GGPubr Boxplot` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/ggpubr-boxplot?lang=zh_cn>
:::

特性丰富的箱线图（GGPubr 接口）。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggpubr`; `ggthemes`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggpubr", quietly = TRUE)) {
  install.packages("ggpubr")
}
if (!requireNamespace("ggthemes", quietly = TRUE)) {
  install.packages("ggthemes")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggpubr)
library(ggthemes)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/ggpubr-boxplot/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 查看数据
head(data)
```

## 可视化

```{r fig-1ggpubr-boxplot}
#| label: fig-1ggpubr-boxplot
#| fig-cap: "GGPubr 箱线图"
#| out.width: "95%"
#| fig-height: 6
#| fig-width: 10
#| warning: false
#| error: false
#| message: false

# GGPubr 箱线图
p <- ggboxplot(
  data = data, x = "supp", y = "len", facet.by = "dose",
  merge = T,
  color = "supp",
  fill = "white") + 
  stat_compare_means(
    label = "p.signif",
    label.x.npc = "center",
    method = "wilcox") + 
  scale_y_continuous(expand = expansion(mult = c(0.2, 0.2))) +
  scale_fill_manual(values = c("#e04d39","#5bbad6")) +
  ggtitle("Complex Boxplot") + 
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```


