---
title: "ggplot2 词云"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `ggwordcloud` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/ggwordcloud?lang=zh_cn>
:::

词云是通过形成“关键字云层”或“关键字渲染”来可视化Web文本中经常出现的“关键字”。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggwordcloud`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggwordcloud", quietly = TRUE)) {
  install.packages("ggwordcloud")
}
if (!requireNamespace("curl", quietly = TRUE)) {
  install.packages("curl")
}
if (!requireNamespace("png", quietly = TRUE)) {
  install.packages("png")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggwordcloud)
library(curl)
library(png)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

加载数据名词和名词频率。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/ggwordcloud/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)
inmask <- "https://download.hiplot.cn/api/file/fetch/?path=public/demo/ggwordcloud/hearth.png"

# 整理数据格式
col <- data[, 2]
data <- cbind(data, col)

# 查看数据
head(data)
```

## 可视化

```{r fig-1ggwordcloud}
#| label: fig-1ggwordcloud
#| fig-cap: "ggplot2 词云"
#| out.width: "95%"
#| fig-height: 7
#| fig-width: 7
#| warning: false
#| error: false
#| message: false

# ggplot2 词云
p <- ggplot(data, aes(label = word, size = freq, color = col)) +
  scale_size_area(max_size = 40) +
  theme_minimal() + 
  geom_text_wordcloud_area(
    mask = png::readPNG(curl::curl_fetch_memory(inmask)$content), 
    rm_outside = TRUE) +
  scale_color_gradient(low = "#8B0000", high = "#FF0000")

p
```

根据名词的频率在词云图中显示名词的比例。


