---
title: "区间区域图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Interval Area Chart` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/interval-area-chart?lang=zh_cn>
:::

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggplot2)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

案例数据为一年十二个月份的最高和最低温度和对应的月份简称。通过案例数据绘制了每个月份的温度区间及温度均线。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/interval-area-chart/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data[["month"]] <- factor(data[["month"]], levels = data[["month"]])

# 查看数据
head(data)
```

## 可视化

```{r fig-1interval-area-chart}
#| label: fig-1interval-area-chart
#| fig-cap: "区间区域图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false
#| error: false
#| message: false

# 区间区域图
p <- ggplot(data, aes(x = month, group = 1)) +
  geom_line(aes(y = max_temperature), size = 1.2, color = "#EA3323", 
            linetype = "solid") +
  geom_line(aes(y = min_temperature), size = 1.2, color = "#0000F5", 
            linetype = "solid") +
  geom_line(aes(x = month, y = mean), size = 1.2, color = "#BEBEBE", 
            linetype = "dashed") +
  geom_ribbon(aes(ymin = min_temperature, ymax = max_temperature), 
              fill = "#F2F2F2", alpha = 0.5) +
  geom_text(aes(x = month, y = max_temperature + 1, label = max_temperature),
            color = "#EA3323", size = 2.5, vjust = -0.5, hjust = 0) +
  geom_text(aes(x = month, y = min_temperature - 1, label = min_temperature),
            color = "#0000F5", size = 2.5, vjust = 1.5, hjust = 0) +
  geom_text(aes(x = month, y = mean, label = mean),
            color = "#BEBEBE", size = 2.5, vjust = 1.5, hjust = 0) +
  labs(title = "Temperature", x = "Month", y = "Temperature") +
  scale_color_manual(values = c(max = "#EA3323", min = "#0000F5")) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

p
```



