---
title: "李克特图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Likert Plot` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/likert?lang=zh_cn>
:::

对李克特量表带数据进行可视化描述性统计分析。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggplotify`; `likert`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}
if (!requireNamespace("likert", quietly = TRUE)) {
  install.packages("likert")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggplotify)
library(likert)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/likert/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
levs <- unique(unlist(data))
for (i in 1:ncol(data)) {
  data[,i] <- factor(data[, i], levels = levs)
}

# 查看数据
head(data)
```

## 可视化

```{r fig-1likert}
#| label: fig-1likert
#| fig-cap: "李克特图"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 8
#| warning: false
#| error: false
#| message: false

# 李克特图
pobj <- likert(data)
colrs <- c("#3B4992FF","#EE0000FF")
p <- as.ggplot(plot(pobj, type = "bar", 
                    low.color = colrs[1], high.color = colrs[2], wrap = 50))

p
```



