---
title: "线图（颜色点）"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Line (Color Dot)` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/line-color-dot?lang=zh_cn>
:::

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `grafify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("grafify", quietly = TRUE)) {
  install.packages("grafify")
}

# 加载包
library(data.table)
library(jsonlite)
library(grafify)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/line-color-dot/data.json")$exampleData[[1]]$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
x <- "Time"
y <- "PI"
group <- "Experiment"
facet <- "Genotype"
data[, x] <- factor(data[, x], levels = unique(data[, x]))
data[, group] <- factor(data[, group], levels = unique(data[, group]))
data[, facet] <- factor(data[, facet], levels = unique(data[, facet]))

# 查看数据
head(data)
```

## 可视化

```{r fig-1line-color-dot}
#| label: fig-1line-color-dot
#| fig-cap: "线图（颜色点）"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 5.5
#| warning: false
#| error: false
#| message: false

# 线图（颜色点）
p <- plot_befafter_colours(
  data = data, xcol = get(x), ycol = get(y), match = get(group),
  symsize = 5, symthick = 1, s_alpha = 1) +
  facet_wrap(facet) +
  guides(fill = guide_legend(title = group)) +
  scale_fill_grafify() +
  xlab(x) + ylab(y) +
  ggtitle("Two-way repeated measures") +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12, hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```


