---
title: "线图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Line` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/line?lang=zh_cn>
:::

线图是指使用线性刻度或对数刻度在二维或三维视图中绘制数据，从而显示数据集或跟踪数据随时间变化的变化特征的统计图表。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggplot2`; `ggthemes`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("ggthemes", quietly = TRUE)) {
  install.packages("ggthemes")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggplot2)
library(ggthemes)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

载入数据为横轴数值及其对应的纵轴数值和分组。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/line/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data[,3] <- factor(data[,3], levels = unique(data[,3]))

# 查看数据
head(data)
```

## 可视化

```{r fig-1line}
#| label: fig-1line
#| fig-cap: "线图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false
#| error: false
#| message: false

# 线图
p <- ggplot(data, aes(x = Value1, y = Value2)) +
  geom_line(alpha = 1, aes(color = Group, linetype = Group)) +
  geom_point(aes(color = Group, shape = Group)) +
  ggtitle("Line Regression Plot") +
  scale_fill_manual(values = c("#e04d39","#5bbad6")) +
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

图示表明治疗方案一中 value1 值与 value2 值呈正相关，而治疗方案二 value1 值与 value2 值呈负相关。


