---
title: "矩阵气泡图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Matrix Bubble` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/matrix-bubble?lang=zh_cn>
:::

彩色矩阵气泡用于可视化不同细胞（列）中多个基因（行）的表达矩阵数据。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggalluvial`; `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggalluvial", quietly = TRUE)) {
  install.packages("ggalluvial")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggalluvial)
library(ggplot2)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

数据结构：

- <1st-col>: (String) 单元格样本名称作为 X 轴
- <2nd-col>: (String) 基因名作为Y轴
- <3rd-col>: (Numeric) 基因表达
- <4rd-col>: (Numeric) 组

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/matrix-bubble/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data[, 1] <- factor(data[, 1], levels = unique(data[, 1]))
data[, 2] <- factor(data[, 2], levels = unique(data[, 2]))

# 查看数据
head(data)
```

## 可视化

```{r fig-1matrix-bubble}
#| label: fig-1matrix-bubble
#| fig-cap: "矩阵气泡图"
#| out.width: "95%"
#| fig-height: 6
#| fig-width: 8
#| warning: false
#| error: false
#| message: false

# 矩阵气泡图
p <- ggplot(data = data, aes(x = x, y = y, size = value, color = y)) +
  geom_point(alpha = 1) +
  labs(title = "Matrix Bubble") +
  guides(color = FALSE) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_line(colour = "gray"),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA),
        panel.spacing = unit(0, "lines"),
        plot.title = element_text(size = 12, hjust = 0.5),
        text = element_text(family = "Arial"),
        legend.title = element_text(size = 10),
        axis.text.x = element_text(angle=0, hjust=0.5, vjust=1)) +
  facet_grid(~group, scales = 'fixed', margins = F) +
  scale_color_manual(values = c(
    "#3B4992FF","#EE0000FF","#008B45FF","#631879FF","#008280FF","#BB0021FF",
    "#5F559BFF","#A20056FF","#808180FF","#1B1919FF"))

p
```


