---
title: "元分析亚组比较"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Meta-Subgroup Analysis` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/metawho?lang=zh_cn>
:::

metawho 的目标是提供“使用元分析方法识别治疗获益最大的人群”的 R 实现。

metawho 由 R 包 metafor 提供支持，目前不支持包含个体的数据集。如果您更熟悉 Stata 代码，请使用 Stata 包 ipdmetan。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `meta`; `cowplot`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("metawho", quietly = TRUE)) {
  install.packages("metawho")
}
if (!requireNamespace("cowplot", quietly = TRUE)) {
  install.packages("cowplot")
}

# 加载包
library(data.table)
library(jsonlite)
library(metawho)
library(cowplot)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/metawho/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data = deft_prepare(data, conf_level = 1 - 0.95)
res = deft_do(data, group_level = unique(data$subgroup))

# 查看数据
head(data)
```

## 可视化

```{r fig-1meta-cont}
#| label: fig-1metawho
#| fig-cap: "元分析亚组比较"
#| out.width: "95%"
#| fig-height: 6
#| fig-width: 8
#| warning: false
#| error: false
#| message: false

# 元分析亚组比较
p1 <- deft_show(res, element = "all")
p2 <- deft_show(res, element = "subgroup")
p <- plot_grid(p1, p2, nrow = 2)

p
```


