---
title: "马赛克比例图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Mosaic Ratio Plot` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/mosaic?lang=zh_cn>
:::

使用马赛克方块展示数据比例。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `vcd`; `DescTools`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("vcd", quietly = TRUE)) {
  install.packages("vcd")
}
if (!requireNamespace("DescTools", quietly = TRUE)) {
  install.packages("DescTools")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# 加载包
library(data.table)
library(jsonlite)
library(vcd)
library(DescTools)
library(ggplotify)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/mosaic/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
tbl <- xtabs(~ Survived + PassengerClass + Gender, data)

# 查看数据
head(data)
```

## 可视化

```{r fig-1mosaic}
#| label: fig-1mosaic
#| fig-cap: "马赛克比例图"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 8
#| warning: false
#| error: false
#| message: false

# 马赛克比例图
p <- as.ggplot(function() {
  mosaic(tbl, shade = TRUE, legend = TRUE, main = "Mosaic Ratio Plot",
         gp = shading_binary(tbl, col = c("#3B4992FF","#EE0000FF")))
})

p
```


