---
title: "诺莫图 (逻辑回归)"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Nomogram (Logistic)` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/nomogram-logistic?lang=zh_cn>
:::

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `rms`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("rms", quietly = TRUE)) {
  install.packages("rms")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# 加载包
library(data.table)
library(jsonlite)
library(rms)
library(ggplotify)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/nomogram-logistic/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
dd <- datadist(data)
options(datadist = "dd")
## 建立 Logistic 模型并运行列线图
logistic_res <- lrm(data=data, as.formula(paste(
    colnames(data)[1], " ~ ",
    paste(colnames(data)[2:length(colnames(data))],
      collapse = "+"
    )
  ))
)
logistic_nomo <- nomogram(logistic_res, maxscale = 100,
  fun= function(x)1/(1+exp(-x)), lp=F, funlabel="Dead Risk",
  fun.at=c(.001,.01,.05,seq(.1,.9,by=.1),.95,.99,.999)
)

# 查看数据
head(data)
```

## 可视化

```{r fig-1nomogram-logistic}
#| label: fig-1nomogram-logistic
#| fig-cap: "诺莫图 (逻辑回归)"
#| out.width: "95%"
#| fig-height: 7
#| fig-width: 8
#| warning: false
#| error: false
#| message: false

# 诺莫图 (逻辑回归)
p <- as.ggplot(function() {
  plot(logistic_nomo,
    scale = 1
  )
  title(main = "Nomogram (Logistic)")
})

p
```


