---
title: "平行坐标图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Parallel Coordinate` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/parallel-coordinate?lang=zh_cn>
:::

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `GGally`; `hrbrthemes`; `viridis`; `ggthemes`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("GGally", quietly = TRUE)) {
  install.packages("GGally")
}
if (!requireNamespace("hrbrthemes", quietly = TRUE)) {
  remotes::install_github("hrbrmstr/hrbrthemes")
}
if (!requireNamespace("viridis", quietly = TRUE)) {
  install.packages("viridis")
}
if (!requireNamespace("ggthemes", quietly = TRUE)) {
  install.packages("ggthemes")
}

# 加载包
library(data.table)
library(jsonlite)
library(GGally)
library(hrbrthemes)
library(viridis)
library(ggthemes)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/parallel-coordinate/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data[, 6] <- factor(data[, 6], levels = unique(data[, 6]))

# 查看数据
head(data)
```

## 可视化

```{r fig-1parallel-coordinate}
#| label: fig-1parallel-coordinate
#| fig-cap: "平行坐标图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 10
#| warning: false
#| error: false
#| message: false

# 平行坐标图
p <- ggparcoord(data, columns = 2:(ncol(data) - 1), groupColumn = ncol(data),
                title = "Parallel Coordinate Plot for cancer Data",
                alphaLines = 0.3, scale = "globalminmax",
                showPoints = T, boxplot = F) +
  theme_base() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12, hjust = 0.5),
        axis.title = element_text(size = 10),
        axis.text = element_text(size = 12),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10)) +
  scale_color_viridis(discrete = TRUE) +
  facet_grid(formula(paste("~", (colnames(data)[ncol(data)]))))

p
```


