---
title: "透视图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Perspective` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/perspective?lang=zh_cn>
:::

三维透视图是一种能将一个矩阵中包含的高等数值用曲面连接起来的三维立体图形。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `shape`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("shape", quietly = TRUE)) {
  install.packages("shape")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# 加载包
library(data.table)
library(jsonlite)
library(shape)
library(ggplotify)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

载入数据为一个矩阵。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/perspective/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data <- as.matrix(data)
col <- drapecol(data)

# 查看数据
head(data[,1:5])
```

## 可视化

```{r fig-1perspective}
#| label: fig-1perspective
#| fig-cap: "透视图"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 5
#| warning: false
#| error: false
#| message: false

# 透视图
p <- as.ggplot(function() {
  persp(as.matrix(data),
    theta = 45, phi = 20,
    expand = 0.5,
    r = 180, col = col,
    ltheta = 120,
    shade = 0.5,
    ticktype = "detailed",
    xlab = "X", ylab = "Y", zlab = "Z",
    border = "black" # could be NA
  )
  title("Perspective Plot", line = 0)
})

p
```

清晰观测一个山峰的全貌。


