---
title: "饼图矩阵"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Pie Matrix` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/pie-matrix?lang=zh_cn>
:::

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggplot2`; `dplyr`; `tidyr`; `stringr`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}
if (!requireNamespace("tidyr", quietly = TRUE)) {
  install.packages("tidyr")
}
if (!requireNamespace("stringr", quietly = TRUE)) {
  install.packages("stringr")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/pie-matrix/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data[,"genre"] <- factor(data[,"genre"], levels = unique(data[,"genre"]))
data[,"mpaa"] <- factor(data[,"mpaa"], levels = unique(data[,"mpaa"]))
data[,"status"] <- factor(data[,"status"], levels = unique(data[,"status"]))
col <- c("#E64B35FF","#4DBBD5FF")
df <- matrix(NA, nrow = length(unique(data[,"mpaa"])),
             ncol = length(unique(data[,"genre"])))
row.names(df) <- unique(data[,"mpaa"])
colnames(df) <- unique(data[,"genre"])
for (i in 1:nrow(df)) {
    for (j in 1:ncol(df)) {
      for (k in unique(data[,"status"])) {
        if (is.na(df[i, j])) {
          df[i, j] <- sum(data[,"genre"] == unique(data[,"genre"])[j] &
            data[,"mpaa"] == unique(data[,"mpaa"])[i] &
            data[,"status"] == k)
        } else {
          df[i, j] <- paste0(df[i, j], ",", 
            sum(data[,"genre"] == unique(data[,"genre"])[j] &
              data[,"mpaa"] == unique(data[,"mpaa"])[i] &
              data[,"status"] == k))
        }
      }
    }
}
df <- as.matrix(df)

# 查看数据
head(data[,1:5])
```

## 可视化

```{r fig-1pie-matrix}
#| label: fig-1pie-matrix
#| fig-cap: "饼图矩阵"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 15
#| warning: false
#| error: false
#| message: false

# 饼图矩阵
p <- df %>% as.table() %>%
  as.data.frame() %>%
  mutate(Freq = str_split(Freq,",")) %>%
  unnest(Freq) %>%
  mutate(Freq = as.integer(Freq)) %>%
  # 将值转换为百分比（每个图表加起来为 1）
  group_by(Var1, Var2) %>%
  mutate(Freq = ifelse(is.na(Freq), NA, Freq / sum(Freq)),
         color = row_number()) %>%
  ungroup() %>%
  # Plot
  ggplot(aes("", Freq, fill=factor(color, labels = unique(data[,"status"])))) + 
  geom_bar(width = 2, stat = "identity") +
  coord_polar("y") +
  facet_wrap(~Var1+Var2, ncol = ncol(df)) +
  scale_fill_manual(values = col) +
  theme_void() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(),
        panel.grid = element_blank(), axis.title = element_blank(),
        legend.position = "bottom", legend.direction = "horizontal") +
  guides(fill = guide_legend(nrow = 1, title = "status"))
  
p
```



