---
title: "饼图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Pie` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/pie?lang=zh_cn>
:::

饼图是通过将一个圆形切分成多个切片以显示每一部分所占总体比例的统计图表。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggplot2`; `dplyr`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggplot2)
library(dplyr)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

载入数据为不同分组及其数据。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/pie/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
colnames(data) <- c("Group", "Value")
data <- data %>%
  arrange(desc(Group)) %>%
  mutate(prop = Value / sum(data$Value) * 100) %>%
  mutate(ypos = Value / length(unique(Group)) +
           c(0, cumsum(Value)[-length(Value)]) + 5)

# 查看数据
head(data)
```

## 可视化

```{r fig-1pie}
#| label: fig-1pie
#| fig-cap: "饼图"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 6
#| warning: false
#| error: false
#| message: false

# 饼图
p <- ggplot(data, aes(x = "", y = Value, fill = Group)) +
  geom_col(width = 1) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  geom_text(aes(y = ypos, 
                label = sprintf("%s\n(n=%s, %s%%)", Group, Value,
                                round(Value / sum(data$Value) * 100, 2))), 
            color = "white", fontface = "bold") +
  coord_polar(theta = "y", start = 0, direction = -1) +
  guides(fill = guide_legend(title = "Group")) +
  scale_fill_discrete(
    breaks = data$Group,
    labels = paste(data$Group," (", round(data$Value / sum(data$Value) * 100, 2),
                   "%)", sep = "")) +
  scale_fill_manual(values = c("#00468BFF","#ED0000FF","#42B540FF","#0099B4FF")) +
  ggtitle("Pie Plot") + 
  theme_minimal() +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    panel.border = element_blank(),
    panel.grid = element_blank(),
    axis.ticks = element_blank(),
    plot.title = element_text(size = 14, face = "bold",
                              hjust = 0.5, vjust = -1),
    legend.position = "none"
  )
    
  
p
```

在一个圆图中，每个切片的弧长（其中心角和中心角所对应区域的弧长）与所表示的数量成正比。该饼图展示了 1~4 组分别的样本数量及样本数量所对应的占比。一组样本数量 13，占比 11.71%，二组样本数量 34，占比 30.63%，三组样本数量 21，占比 18.92%，四组样本数量 43，占比38.74%。

