---
title: "点图（标准差）"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Point (SD)` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/point-sd?lang=zh_cn>
:::

用于展示多组数据点标准差。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `grafify`; `dplyr`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("grafify", quietly = TRUE)) {
  install.packages("grafify")
}
if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}

# 加载包
library(data.table)
library(jsonlite)
library(grafify)
library(dplyr)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/point-sd/data.json")$exampleData[[1]]$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
y <- "Doubling_time"
group <- "Student"
data[, group] <- factor(data[, group], levels = unique(data[, group]))
data <- data %>% 
  mutate(median = median(get(y), na.rm = TRUE),
         mean = mean(get(y), na.rm = TRUE))

# 查看数据
head(data)
```

## 可视化

```{r fig-1point-sd}
#| label: fig-1point-sd
#| fig-cap: "点图（标准差）"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false
#| error: false
#| message: false

# 点图（标准差）
p <- plot_point_sd(data = data, Student, Doubling_time, symsize = 5,
                   symthick = 0.5, s_alpha = 1, ewid = 0, symshape = 21,
                   all_alpha = 0) +
  geom_hline(aes(yintercept = median), colour = 'black', linetype = 2, 
             size = 0.5) +
  xlab(group) + ylab(y) + 
  guides(fill = guide_legend(title = group)) +
  ggtitle("Point-SD") +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))
    
  
p
```


