---
title: "金字塔图 2"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Pyramid Chart 2` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/pyramid-chart2?lang=zh_cn>
:::

金字塔图是一种将数据分布于中轴两侧类似金字塔的图形。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `apyramid`; `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("apyramid", quietly = TRUE)) {
  install.packages("apyramid")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# 加载包
library(data.table)
library(jsonlite)
library(apyramid)
library(ggplot2)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

载入数据为年龄段，性别分类及前两种变量组合后的人口数目。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/pyramid-chart2/data.json")$exampleData[[1]]$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
x <- as.integer(data[,"age"])
data$age_group <- cut(x, breaks = pretty(x), right = TRUE, include.lowest = TRUE)

# 查看数据
head(data[,1:5])
```

## 可视化

```{r fig-1pyramid-chart2}
#| label: fig-1pyramid-chart2
#| fig-cap: "金字塔图2"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 7
#| warning: false
#| error: false
#| message: false

# 金字塔图2
p <- age_pyramid(data, "age_group", split_by = "Gender") + 
  scale_fill_manual(values = c("#BC3C29FF","#0072B5FF")) +
  xlab("Age group") + 
  ylab("Gender") +
  theme_classic() +
  theme(text = element_text(family = "Arial"),
      plot.title = element_text(size = 12,hjust = 0.5),
      axis.title = element_text(size = 12),
      axis.text = element_text(size = 10),
      axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
      legend.position = "right",
      legend.direction = "vertical",
      legend.title = element_text(size = 10),
      legend.text = element_text(size = 10))

p
```

图示将年龄段按照顺序从下到上依次显示在中轴线上，左侧表示男性人数，右侧表示女性人数，x 轴表示人口数量，该图可以很明显看出男女在不同年龄段的人数占比情况以及相同性别中不同年龄组的占比情况。



