---
title: "金字塔堆叠图2"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Pyramid Stack2` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/pyramid-stack2?lang=zh_cn>
:::

金字塔堆叠图可以用于展示年龄组多变量。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `plotrix`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("plotrix", quietly = TRUE)) {
  install.packages("plotrix")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# 加载包
library(data.table)
library(jsonlite)
library(plotrix)
library(ggplotify)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/pyramid-stack2/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
agegrps <- unique(data[,1])
split_var <- unique(data[,2])
dat_left <- as.matrix(data[data[,2] == split_var[1],-c(1,2)])
dat_right <- as.matrix(data[data[,2] == split_var[2],-c(1,2)])

# 查看数据
head(data)
```

## 可视化

```{r fig-1pyramid-stack2}
#| label: fig-1pyramid-stack2
#| fig-cap: "金字塔堆叠图2"
#| out.width: "95%"
#| fig-height: 7
#| fig-width: 9
#| warning: false
#| error: false
#| message: false

# 金字塔堆叠图2
p <- as.ggplot(function() {
  cols <- c("#E64B35FF","#4DBBD5FF","#00A087FF","#3C5488FF")
  names(cols) <- colnames(dat_left)
  cols <- cols[1:ncol(dat_left)]
  pyramid.plot(dat_left, dat_right, labels = agegrps, unit = "Value",
               lxcol = cols, rxcol = cols,
               laxlab=as.numeric(c(0,10,20,30)), raxlab=as.numeric(c(0,10,20,30)),
               top.labels=c(split_var[1], colnames(data)[1], split_var[2]),
               gap=4, ppmar=c(4,2,4,7), do.first="plot_bg(\"#FFFFFF\")")
  mtext("Porridge temperature by age and sex of bear", 3, 2, cex=1)
  legend("right", inset=c(-0.25,0), legend = colnames(dat_left), fill = cols)
  })

p
```



