---
title: "QQ 图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `QQ Plot` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/qqplot?lang=zh_cn>
:::

用于直观验证一组数据是否来自某个分布，或者验证某两组数据是否来自同一（族）分布。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `grafify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("grafify", quietly = TRUE)) {
  install.packages("grafify")
}

# 加载包
library(data.table)
library(jsonlite)
library(grafify)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/qqplot/data.json")$exampleData[[1]]$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data[, "Genotype"] <- factor(data[, "Genotype"], levels = unique(data[, "Genotype"]))

# 查看数据
head(data)
```

## 可视化

```{r fig-1qqplot}
#| label: fig-1qqplot
#| fig-cap: "QQ 图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 5.5
#| warning: false
#| error: false
#| message: false

# QQ 图
p <- plot_qqline(data = data, ycol = Cytokine, group = Genotype,
                 symsize = 2, symthick = 0.5, s_alpha = 1) +
  ggtitle("QQplot without facet") +
  xlab("theoretical") + ylab("sample") + 
  guides(fill = guide_legend(title = "Genotype")) +
  scale_color_manual(values = c("#E69F00","#4DB1DC")) +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```



