---
title: "丝带图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Ribbon` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/ribbon?lang=zh_cn>
:::

丝带图是一种类似丝带的图形。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggplot2`; `ggthemes`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("ggthemes", quietly = TRUE)) {
  install.packages("ggthemes")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggplot2)
library(ggthemes)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

载入数据为 x 轴数值及其对应的两个 y 轴数值和分组。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/ribbon/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
colnames(data) <- c("group", "xvalue", "yvalue1", "yvalue2")
data$yvalue <- (data$yvalue1 + data$yvalue2) / 2

# 查看数据
head(data)
```

## 可视化

```{r fig-1ribbon}
#| label: fig-1ribbon
#| fig-cap: "丝带图"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 8
#| warning: false
#| error: false
#| message: false

# 丝带图
p <- ggplot(data, aes(xvalue, yvalue, fill = group)) +
  geom_ribbon(alpha = 0.2, aes(ymin = yvalue1, ymax = yvalue2)) +
  geom_line(aes(y = yvalue, color = group), lwd = 1) +
  geom_line(aes(y = yvalue1, color = group), linetype = "dotted") +
  geom_line(aes(y = yvalue2, color = group), linetype = "dotted") +
  ylab("y axis value") +
  xlab("x axis value") +
  ggtitle("Ribbon Plot") +
  scale_fill_manual(values = c("#e04d39","#5bbad6")) +
  scale_color_manual(values = c("#e04d39","#5bbad6")) +
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))
 
p
```

每种颜色表示不同的分组，可以透过其中折线，观测每组数据随时间的变化。



