---
title: "岭图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Ridge` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/ridge?lang=zh_cn>
:::

岭图是一种将点连接围成形似山岭的图形。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggridges`; `ggplot2`; `ggthemes`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggridges", quietly = TRUE)) {
  install.packages("ggridges")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("ggthemes", quietly = TRUE)) {
  install.packages("ggthemes")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggridges)
library(ggplot2)
library(ggthemes)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

载入数据为三种分组及其对应的数值。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/ridge/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data$group <- factor(data$group, levels = unique(data$group)[length(unique(data$group)):1])

# 查看数据
head(data)
```

## 可视化

```{r fig-1ridge}
#| label: fig-1ridge
#| fig-cap: "岭图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 8
#| warning: false
#| error: false
#| message: false

# 岭图
p <- ggplot(data, aes(x = value, y = group, fill = group, col = group)) +
  geom_density_ridges(scale = 5, alpha = 0.8) +
  labs(x = "value", y = "group") +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  ggtitle("Ridge Plot") +
  guides(color = guide_legend(reverse = TRUE),
         fill = guide_legend(reverse = TRUE)) +
  scale_fill_manual(values = c("#e04d39","#5bbad6","#1e9f86")) +
  scale_color_manual(values = c("#e04d39","#5bbad6","#1e9f86")) +
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

不同颜色表示不同分组，可以观测数据大致的高低程度。



