---
title: "三维散点图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `3D Scatter` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/scatter-3d?lang=zh_cn>
:::

三维散点图是将多个定量变量运用于空间中的不同轴上，并将不同的变量组合成空间中的坐标，从而对三个定量变量的交互关系进行清晰的解释。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `plot3D`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("plot3D", quietly = TRUE)) {
  install.packages("plot3D")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# 加载包
library(data.table)
library(jsonlite)
library(plot3D)
library(ggplotify)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

载入数据为三个变量和分组。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/scatter-3d/data.json")$exampleData[[1]]$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
col_idx <- which(colnames(data) == "group")
data[, col_idx] <- as.factor(data[, col_idx])
shapes <- 19
shape_idx <- ""

# 查看数据
head(data)
```

## 可视化

```{r fig-1scatter-3d}
#| label: fig-1scatter-3d
#| fig-cap: "三维散点图"
#| out.width: "95%"
#| fig-height: 6
#| fig-width: 8
#| warning: false
#| error: false
#| message: false

# 三维散点图
p <- as.ggplot(function() {
  plot3d <- scatter3D(data[, 1], data[, 2], data[, 3],
    pch = shapes, cex = 1,
    phi = 0, theta = 45, ticktype = "detailed",
    bty = "b2", colkey = FALSE, alpha = 1,
    xlab = colnames(data)[1], ylab = colnames(data)[2],
    zlab = colnames(data)[3],
    main = "3D-Scatter Plot",
    colvar = as.numeric(as.factor(data[, 4])),
    col = c("#e04d39","#5bbad6","#1e9f86")
  )
  
  legend("right", pch=19, legend = levels(data[, col_idx]),
         cex = 1.1, bty = 'n', xjust = 0.5, horiz = F,
         title = colnames(data)[col_idx],
         col = c("#e04d39","#5bbad6","#1e9f86"))
})

p
```

图中分别将温度、压力、时间放置在 x（水平轴）、y（垂直轴）、z（透视轴）上，生成一幅三维散点图，直观发现三者变量间的相关关系及相关强弱程度。



