---
title: "渐变散点图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Gradient Scatter` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/scatter-gradient?lang=zh_cn>
:::

二维空间散点展示多数值变量关系。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `grafify`; `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("grafify", quietly = TRUE)) {
  install.packages("grafify")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# 加载包
library(data.table)
library(jsonlite)
library(grafify)
library(ggplot2)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/scatter-gradient/data.json")$exampleData[[1]]$textarea[[1]])
data <- as.data.frame(data)

# 查看数据
head(data[,1:5])
```

## 可视化

```{r fig-1scatter-gradient}
#| label: fig-1scatter-gradient
#| fig-cap: "渐变散点图"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 8
#| warning: false
#| error: false
#| message: false

# 渐变散点图
p <- ggplot(data, aes(x = mpg, y = disp)) + 
  geom_point(aes(fill = gear), size = 5, alpha = 1, shape = 21, stroke = 0.5) +
  labs(fill = "gear", color = "gear") +
  theme_classic(base_size = 10) +
  theme(strip.background = element_blank()) +
  guides(x = guide_axis(angle = 0)) +
  scale_fill_gradient(low = "#00438E", high = "#E43535") +
  scale_color_gradient(low = "#00438E", high = "#E43535") + 
  guides(fill = guide_legend(title = "gear"),
         size = guide_legend(title = "gear")) +
  ggtitle("Scatter-gradient Plot") +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```





