---
title: "流动图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Streamgraph` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/streamgraph?lang=zh_cn>
:::

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `streamgraph`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("streamgraph", quietly = TRUE)) {
  remotes::install_github("hrbrmstr/streamgraph")
}

# 加载包
library(data.table)
library(jsonlite)
library(streamgraph)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/streamgraph/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
colnames(data) <- c("date","key","value")

# 查看数据
head(data)
```

## 可视化

```{r fig-1streamgraph}
#| label: fig-1streamgraph
#| fig-cap: "流动图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 8
#| warning: false
#| error: false
#| message: false

# 流动图
p <- streamgraph(data, key = "key", value = "value", date = "date",
                 offset = "silhouette", interpolate = "cardinal",
                 interactive = F, scale = "date") %>% 
  sg_fill_brewer(palette = "Spectral")

p
```


