---
title: "双分组小提琴图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Violin Group` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/violin-group?lang=zh_cn>
:::

T检验分组数据的小提琴图和盒图。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `ggpubr`; `ggthemes`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggpubr", quietly = TRUE)) {
  install.packages("ggpubr")
}
if (!requireNamespace("ggthemes", quietly = TRUE)) {
  install.packages("ggthemes")
}

# 加载包
library(data.table)
library(jsonlite)
library(ggpubr)
library(ggthemes)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

- <1st col>：（数字）值数据
- <2nd col>：（String）第1列组
- <3rd col>：（字符串）第2列组

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/violin-group/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
data[, 3] <- factor(data[, 3], levels = unique(data[, 3]))

# 查看数据
head(data)
```

## 可视化

```{r fig-1violin-group}
#| label: fig-1violin-group
#| fig-cap: "双分组小提琴图"
#| out.width: "95%"
#| fig-height: 6
#| fig-width: 8
#| warning: false
#| error: false
#| message: false

# 双分组小提琴图
p <- ggviolin(data, x = "Group1", y = "Value", color = "Group2", add = "dotplot",
              add.params = list(fill = "white",size = 1), title = "Violin Diagram",
              xlab = "Group1", ylab = "Value", fill = "Group2",
              palette = c("#374E55FF", "#DF8F44FF"), alpha = 0.5, trim = F) +
  stat_compare_means(aes(group = data[, colnames(data)[3]]),
    method = "t.test", vjust = -6, label.x.npc = "left", label.y.npc = "top",
    tip.length = 0.03, bracket.size = 0.3, step.increase = 0, position = "identity",
    na.rm = FALSE, show.legend = NA, inherit.aes = TRUE, geom = "text") +
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```



