---
title: "数据概览图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Visdat` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/visdat?lang=zh_cn>
:::

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `visdat`; `ggplot2`; `dplyr`; `patchwork`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("visdat", quietly = TRUE)) {
  install.packages("visdat")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}
if (!requireNamespace("patchwork", quietly = TRUE)) {
  install.packages("patchwork")
}

# 加载包
library(data.table)
library(jsonlite)
library(visdat)
library(ggplot2)
library(dplyr)
library(patchwork)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/visdat/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 查看数据
head(data)
```

## 可视化

```{r fig-1visdat}
#| label: fig-1visdat
#| fig-cap: "数据概览图"
#| out.width: "95%"
#| fig-height: 10
#| fig-width: 10
#| warning: false
#| error: false
#| message: false

# 数据概览图
add_palette <- function (p) {
  ## 添加配色
  p <- p + scale_fill_manual(values = c("#3B4992FF", "#EE0000FF"))
}
pobj <- list()
pobj[["p1"]] <- add_palette(vis_dat(data)) + ggtitle(':vis_dat')
pobj[["p2"]] <- add_palette(vis_guess(data)) + ggtitle(':vis_guess')
pobj[["p3"]] <- vis_miss(data, cluster = T, sort_miss = T) + ggtitle(':vis_miss')
pobj[["p4"]] <- add_palette(vis_expect(data, ~.x >= 20 )) + ggtitle(':vis_expect')
pobj[["p5"]] <- vis_cor(data) + 
  scale_fill_gradientn(colours = c("#0571B0", "#92C5DE", "#F4A582", "#CA0020")) +
  ggtitle(':vis_cor')
pobj[["p6"]] <- data %>%
      select_if(is.numeric) %>%
      vis_value() + ggtitle(':vis_value')
pobj[["p6"]] <- pobj[["p6"]] + 
  scale_fill_gradientn(colours = c("#0571B0","#92C5DE","#F7F7F7","#F4A582",
                                   "#CA0020"))

pstr <- paste0(sprintf("pobj[[%s]]", 1:length(pobj)), collapse = " + ")
p <- eval(parse(text = 
  sprintf("%s + plot_layout(ncol = 2) +
plot_annotation(tag_levels = 'A')", pstr)))

p
```



