---
title: "瀑布图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
  - "**[审核]** ."
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Waterfalls` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/waterfalls?lang=zh_cn>
:::

瀑布图用于显示顺序引入正值或负值的累积效应。这些中间值可以基于时间或基于类别。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `waterfalls`; `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("waterfalls", quietly = TRUE)) {
  install.packages("waterfalls")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# 加载包
library(data.table)
library(jsonlite)
library(waterfalls)
library(ggplot2)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

加载的数据具有两个列，其中第一个针对类别的项目，第二个针对其相应的值。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/waterfalls/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 查看数据
head(data)
```

## 可视化

```{r fig-1waterfalls}
#| label: fig-1waterfalls
#| fig-cap: "瀑布图"
#| out.width: "95%"
#| fig-height: 6
#| fig-width: 8
#| warning: false
#| error: false
#| message: false

# 瀑布图
p <- waterfall(data, rect_text_labels = data$value, rect_text_size = 1,
    rect_text_labels_anchor = "centre", calc_total = T,
    total_axis_text = "Total", total_rect_text = sum(data$value),
    total_rect_color = "steelblue", total_rect_text_color = "black",
    rect_width = 0.7, rect_border = "black", draw_lines = TRUE,
    linetype = 2, fill_by_sign = F, 
    fill_colours = c("#E64B35FF","#4DBBD5FF","#00A087FF","#3C5488FF","#F39B7FFF",
                     "#8491B4FF"),
    scale_y_to_waterfall = T) +
  theme_bw() +
  theme(axis.text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "Waterfalls Plot")

p
```

如示例图所示，X轴表示每个基于类别的项目，y轴显示其累积值。足够极端的增量和减小会导致累积总数在各个点上方降低和低于轴的高于轴的上方。


